// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220911135635_init1")]
    partial class init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 814, DateTimeKind.Local).AddTicks(8544),
                            Details = "Consequatur quidem consectetur praesentium ullam voluptatem distinctio cupiditate sit dolor quia sunt deserunt ea.",
                            ImageUrl = "https://i.picsum.photos/id/778/200/200.jpg?hmac=fgFK_HI_g_N4MzYuYbssOB8ymhT_m0JK61tNJHfdPYU",
                            Name = "Nicolas Schuppe",
                            Occupancy = 3,
                            Rate = 14.0,
                            Sqft = 431,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 815, DateTimeKind.Local).AddTicks(1060),
                            Details = "Ipsam voluptatum suscipit voluptates quos iusto sint qui vel tempora.",
                            ImageUrl = "https://i.picsum.photos/id/287/200/200.jpg?hmac=kXFCSMZE2rF7NM-EFSH6c_nl5HlKQWvwCdE8JYL-YNQ",
                            Name = "Maurice Russel",
                            Occupancy = 4,
                            Rate = 11.0,
                            Sqft = 308,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 815, DateTimeKind.Local).AddTicks(3939),
                            Details = "Quas non tempora molestiae officiis aut velit et natus blanditiis sed vitae ut.",
                            ImageUrl = "https://i.picsum.photos/id/446/200/200.jpg?hmac=PkaLcCtgL4IvAz-gsxbCXz_tl0qdVUGOrxhYLrywa-c",
                            Name = "Candido Mraz",
                            Occupancy = 7,
                            Rate = 12.0,
                            Sqft = 386,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 815, DateTimeKind.Local).AddTicks(6970),
                            Details = "Dolorem aliquam corrupti autem aut in non molestiae nihil labore consequatur qui ipsum ullam veritatis.",
                            ImageUrl = "https://i.picsum.photos/id/602/200/200.jpg?hmac=UQpVCHEMGI1-S-kt8OQLic6TfuG2elfLbLTNDl1mqZE",
                            Name = "Oma Wilderman",
                            Occupancy = 3,
                            Rate = 8.0,
                            Sqft = 401,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 815, DateTimeKind.Local).AddTicks(9562),
                            Details = "Quos occaecati aut sapiente quia laudantium quas non incidunt aliquam sequi.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Junius Blick",
                            Occupancy = 4,
                            Rate = 5.0,
                            Sqft = 146,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 816, DateTimeKind.Local).AddTicks(2073),
                            Details = "Accusamus architecto nostrum provident ea in occaecati quod possimus sed.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Dorris McKenzie",
                            Occupancy = 3,
                            Rate = 7.0,
                            Sqft = 434,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 816, DateTimeKind.Local).AddTicks(4919),
                            Details = "Dolorem nostrum ipsa deleniti sit voluptas blanditiis sapiente quia neque tenetur enim eligendi.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Foster Auer V",
                            Occupancy = 10,
                            Rate = 2.0,
                            Sqft = 323,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 816, DateTimeKind.Local).AddTicks(7541),
                            Details = "Quis a perspiciatis ab quos deleniti quibusdam amet fugiat et reiciendis.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Mr. Joelle Murphy",
                            Occupancy = 6,
                            Rate = 16.0,
                            Sqft = 185,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 817, DateTimeKind.Local).AddTicks(1910),
                            Details = "Vel maiores sequi quo quod quasi nesciunt quo ut maxime voluptatem voluptas veritatis dicta maxime porro.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Dr. Guiseppe Raina Schaefer",
                            Occupancy = 7,
                            Rate = 2.0,
                            Sqft = 180,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 817, DateTimeKind.Local).AddTicks(4415),
                            Details = "Reiciendis sunt aperiam et perspiciatis nesciunt quisquam voluptatem asperiores eligendi.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Lourdes Barrows",
                            Occupancy = 8,
                            Rate = 15.0,
                            Sqft = 400,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 817, DateTimeKind.Local).AddTicks(7138),
                            Details = "Ducimus tempore asperiores non occaecati et quam perspiciatis repellat autem inventore tempore eaque.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Jarrell Bogisich",
                            Occupancy = 10,
                            Rate = 10.0,
                            Sqft = 458,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 818, DateTimeKind.Local).AddTicks(102),
                            Details = "Asperiores sed vitae modi qui sed voluptatem omnis cupiditate voluptatem neque molestiae autem voluptates tempore.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Hailey Hayes",
                            Occupancy = 3,
                            Rate = 14.0,
                            Sqft = 296,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 818, DateTimeKind.Local).AddTicks(3242),
                            Details = "Voluptatum dolorum explicabo omnis inventore nam eos est sed ab rem aut harum eos odio nesciunt.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Shanel Nienow IV",
                            Occupancy = 8,
                            Rate = 18.0,
                            Sqft = 137,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 818, DateTimeKind.Local).AddTicks(7325),
                            Details = "Velit odit sunt numquam accusantium nihil voluptas sunt officiis inventore adipisci alias et.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Pearline Friedrich Hyatt Jr.",
                            Occupancy = 10,
                            Rate = 13.0,
                            Sqft = 126,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 819, DateTimeKind.Local).AddTicks(286),
                            Details = "Modi occaecati perferendis iste velit ratione et at qui ut soluta odit autem sunt et.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Mariah Rogahn",
                            Occupancy = 4,
                            Rate = 14.0,
                            Sqft = 205,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 819, DateTimeKind.Local).AddTicks(3424),
                            Details = "Totam ex nobis qui harum consequuntur ad et ullam et amet et minima omnis atque sunt.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Samanta Auer",
                            Occupancy = 8,
                            Rate = 2.0,
                            Sqft = 286,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 819, DateTimeKind.Local).AddTicks(6115),
                            Details = "Aut possimus dignissimos in et ab cum doloribus dolores tempora aut laborum.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Jessica Streich",
                            Occupancy = 3,
                            Rate = 4.0,
                            Sqft = 316,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 819, DateTimeKind.Local).AddTicks(8826),
                            Details = "Eveniet ipsa quos voluptatem et voluptatem architecto corporis neque nulla dolore ea similique.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Deshaun Berge III",
                            Occupancy = 1,
                            Rate = 7.0,
                            Sqft = 110,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 820, DateTimeKind.Local).AddTicks(1740),
                            Details = "Tempore enim ea voluptatum non quaerat consequatur neque fugiat ut nostrum unde rerum.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Ms. Elta Mann",
                            Occupancy = 8,
                            Rate = 19.0,
                            Sqft = 279,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 820, DateTimeKind.Local).AddTicks(5864),
                            Details = "Porro similique aperiam reiciendis qui nesciunt recusandae quia in velit quae et veniam.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Dr. Kamren Hildegard West III",
                            Occupancy = 7,
                            Rate = 16.0,
                            Sqft = 492,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 820, DateTimeKind.Local).AddTicks(9855),
                            Details = "Officia quasi laudantium laboriosam porro id rem ut eveniet vitae cupiditate.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Bryana Flo Frami Jr.",
                            Occupancy = 9,
                            Rate = 13.0,
                            Sqft = 209,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 821, DateTimeKind.Local).AddTicks(2531),
                            Details = "Quis qui voluptatem voluptatem id delectus consequuntur aut optio excepturi voluptas.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Stone Metz",
                            Occupancy = 1,
                            Rate = 5.0,
                            Sqft = 156,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 821, DateTimeKind.Local).AddTicks(5377),
                            Details = "Ipsa nihil hic qui voluptatibus voluptas ut voluptatum explicabo dolores rerum sed similique.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Nyah Kunde",
                            Occupancy = 5,
                            Rate = 9.0,
                            Sqft = 167,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 821, DateTimeKind.Local).AddTicks(8622),
                            Details = "Sequi ea voluptates ut provident optio ut velit porro excepturi aperiam quia natus nemo.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Sonya Rempel",
                            Occupancy = 6,
                            Rate = 2.0,
                            Sqft = 222,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 822, DateTimeKind.Local).AddTicks(1753),
                            Details = "Eaque voluptatum accusantium libero unde nihil eius repellat maiores magni possimus et iste aliquam aut.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Dr. Anika Wiegand",
                            Occupancy = 4,
                            Rate = 16.0,
                            Sqft = 220,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 822, DateTimeKind.Local).AddTicks(4656),
                            Details = "Neque consequatur non corporis ut alias facere tempore quisquam dolore sed.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Sydnee Hauck",
                            Occupancy = 8,
                            Rate = 1.0,
                            Sqft = 226,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 822, DateTimeKind.Local).AddTicks(7393),
                            Details = "Amet corrupti totam dolores eligendi voluptatem et fugit quo quo.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Jessyca Will",
                            Occupancy = 2,
                            Rate = 8.0,
                            Sqft = 295,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 823, DateTimeKind.Local).AddTicks(66),
                            Details = "Deleniti et quae veritatis et placeat corporis illum similique qui.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Dr. Oscar Kuhn PhD",
                            Occupancy = 5,
                            Rate = 16.0,
                            Sqft = 169,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 823, DateTimeKind.Local).AddTicks(2712),
                            Details = "Dolorem et sequi recusandae eligendi cupiditate quibusdam ea sapiente voluptatem aut.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Jerome Shields",
                            Occupancy = 1,
                            Rate = 8.0,
                            Sqft = 333,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 823, DateTimeKind.Local).AddTicks(5882),
                            Details = "Modi totam qui cum sunt et est itaque magni enim illum sint quis aliquam.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Ora Hansen",
                            Occupancy = 6,
                            Rate = 5.0,
                            Sqft = 363,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 823, DateTimeKind.Local).AddTicks(8742),
                            Details = "Nemo hic numquam aut reiciendis minima quo ea qui error dolores laboriosam veritatis.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Dr. Earnestine Bednar",
                            Occupancy = 4,
                            Rate = 8.0,
                            Sqft = 158,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 824, DateTimeKind.Local).AddTicks(1981),
                            Details = "Qui autem suscipit harum natus sunt consequatur non sunt saepe ipsam architecto sed enim sit.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Jedediah Homenick",
                            Occupancy = 5,
                            Rate = 19.0,
                            Sqft = 190,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 824, DateTimeKind.Local).AddTicks(4887),
                            Details = "Est necessitatibus porro officia inventore cum nihil numquam asperiores dolor veritatis nam.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Buford Cronin",
                            Occupancy = 4,
                            Rate = 15.0,
                            Sqft = 401,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 824, DateTimeKind.Local).AddTicks(7637),
                            Details = "Voluptates ipsam debitis est quas repudiandae sint sit dolor aut ex.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Mr. Stanton Swaniawski",
                            Occupancy = 9,
                            Rate = 8.0,
                            Sqft = 436,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 825, DateTimeKind.Local).AddTicks(728),
                            Details = "Accusamus et maiores et consectetur consequatur mollitia quasi quae consequatur culpa quis ipsa dolorem ipsam nisi.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Ken Hahn DDS",
                            Occupancy = 2,
                            Rate = 14.0,
                            Sqft = 341,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 825, DateTimeKind.Local).AddTicks(3286),
                            Details = "Aliquam aliquam est architecto eum sunt labore quo ipsa placeat velit.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Prof. Reva Rippin Jr.",
                            Occupancy = 10,
                            Rate = 18.0,
                            Sqft = 408,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 825, DateTimeKind.Local).AddTicks(5884),
                            Details = "Perspiciatis et eaque et fugiat maiores cupiditate totam iure nihil libero.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Gladyce Murazik",
                            Occupancy = 1,
                            Rate = 14.0,
                            Sqft = 450,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 825, DateTimeKind.Local).AddTicks(8856),
                            Details = "Dicta fuga laboriosam molestiae maxime ratione sapiente omnis esse soluta officia illo fugiat dolorum assumenda.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Lora Koepp",
                            Occupancy = 7,
                            Rate = 6.0,
                            Sqft = 483,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 826, DateTimeKind.Local).AddTicks(1563),
                            Details = "Aliquid eius ducimus atque inventore provident quia fugiat corporis architecto odit rerum.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Miss Bud Stokes DDS",
                            Occupancy = 2,
                            Rate = 1.0,
                            Sqft = 190,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 826, DateTimeKind.Local).AddTicks(4382),
                            Details = "Ut sed aut rerum fugiat iusto eum at unde error totam qui autem perferendis.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Otis Padberg IV",
                            Occupancy = 6,
                            Rate = 17.0,
                            Sqft = 430,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("VillaNo");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            VillaNo = 101,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 812, DateTimeKind.Local).AddTicks(944),
                            SpecialDetails = "Placeat rerum deserunt est voluptas similique soluta odio consequatur et placeat.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 102,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 812, DateTimeKind.Local).AddTicks(2484),
                            SpecialDetails = "Pariatur quis aut repellendus eum suscipit quis ad blanditiis accusamus amet ipsam corporis dolores labore quos.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 103,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 812, DateTimeKind.Local).AddTicks(3770),
                            SpecialDetails = "Aut et dignissimos quidem qui sunt assumenda consequuntur explicabo velit repellendus error sed.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 104,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 812, DateTimeKind.Local).AddTicks(4729),
                            SpecialDetails = "Rerum sapiente est fugit provident nostrum laboriosam occaecati sit praesentium.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 105,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 812, DateTimeKind.Local).AddTicks(5689),
                            SpecialDetails = "Itaque occaecati earum accusantium nesciunt eum illum vel maiores expedita.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 106,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 812, DateTimeKind.Local).AddTicks(7107),
                            SpecialDetails = "Ducimus sunt in ipsam quia et sed quo incidunt omnis explicabo saepe quidem qui sint.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 107,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 812, DateTimeKind.Local).AddTicks(8500),
                            SpecialDetails = "Aut fuga dolorem blanditiis eligendi vel quam qui aperiam in officia non minus impedit voluptatem.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 109,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 813, DateTimeKind.Local).AddTicks(1176),
                            SpecialDetails = "Consectetur doloribus eligendi et ut aliquam voluptates unde rerum quia quam temporibus ut rerum velit est.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 110,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 813, DateTimeKind.Local).AddTicks(2535),
                            SpecialDetails = "Sed atque praesentium qui repellendus qui est velit voluptatem eos cum enim ut.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 201,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 813, DateTimeKind.Local).AddTicks(3719),
                            SpecialDetails = "Omnis est aut a minima quae aut voluptatem debitis non error odio.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 202,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 813, DateTimeKind.Local).AddTicks(4874),
                            SpecialDetails = "Recusandae molestiae ea possimus illum est commodi nam perspiciatis beatae sequi quod.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 203,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 813, DateTimeKind.Local).AddTicks(6276),
                            SpecialDetails = "Eaque ut quod nesciunt aut voluptatem et distinctio quasi incidunt minus facilis quos voluptas mollitia.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 204,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 813, DateTimeKind.Local).AddTicks(7637),
                            SpecialDetails = "Illum quia saepe excepturi aut et id dolores aperiam error quas sit dolor commodi.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 205,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 813, DateTimeKind.Local).AddTicks(9086),
                            SpecialDetails = "Eum explicabo rem ea tenetur qui possimus vitae sunt non voluptatibus esse corporis aut exercitationem.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 206,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 814, DateTimeKind.Local).AddTicks(187),
                            SpecialDetails = "Voluptas rerum nam nemo aut repellat illum in molestias exercitationem consequatur.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 207,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 814, DateTimeKind.Local).AddTicks(1629),
                            SpecialDetails = "Quisquam porro aut explicabo soluta similique accusamus consequatur sed iste porro eaque facilis doloremque aperiam.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 208,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 814, DateTimeKind.Local).AddTicks(3226),
                            SpecialDetails = "Facilis asperiores est rerum quod ut et provident eius commodi ut necessitatibus reiciendis voluptas dolorem officia.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 209,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 814, DateTimeKind.Local).AddTicks(4175),
                            SpecialDetails = "Corporis amet consequatur autem rem in sapiente sed officia inventore.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 210,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 56, 34, 814, DateTimeKind.Local).AddTicks(5232),
                            SpecialDetails = "Dolorem velit ab blanditiis libero earum qui sunt mollitia nisi aut.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        });
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.HasOne("MagicVilla_VillaAPI.Models.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
