// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220917141601_initDb")]
    partial class initDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Et nobis in perspiciatis modi qui commodi saepe quo accusamus et sequi voluptatem voluptatem eos deleniti.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 811, DateTimeKind.Local).AddTicks(1370),
                            Details = "Eum voluptatibus cupiditate et debitis qui voluptates aut ipsum ut deserunt tempora tempora officia quisquam.",
                            ImageUrl = "https://i.picsum.photos/id/778/200/200.jpg?hmac=fgFK_HI_g_N4MzYuYbssOB8ymhT_m0JK61tNJHfdPYU",
                            Name = "Alyce Hickle",
                            Occupancy = 7,
                            Rate = 15.0,
                            Sqft = 269,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Corporis nisi eligendi laboriosam in facere consequuntur rem eius et omnis fuga ipsum consequatur.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 811, DateTimeKind.Local).AddTicks(5251),
                            Details = "Vero nihil commodi recusandae voluptatibus molestiae provident omnis natus accusantium.",
                            ImageUrl = "https://i.picsum.photos/id/287/200/200.jpg?hmac=kXFCSMZE2rF7NM-EFSH6c_nl5HlKQWvwCdE8JYL-YNQ",
                            Name = "Shea Osinski",
                            Occupancy = 6,
                            Rate = 11.0,
                            Sqft = 109,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Et nisi vitae sed est aperiam velit eveniet sequi pariatur provident vel.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 811, DateTimeKind.Local).AddTicks(8888),
                            Details = "Architecto dolores beatae ut enim et dolorum et corporis atque explicabo.",
                            ImageUrl = "https://i.picsum.photos/id/446/200/200.jpg?hmac=PkaLcCtgL4IvAz-gsxbCXz_tl0qdVUGOrxhYLrywa-c",
                            Name = "Luz Keebler",
                            Occupancy = 6,
                            Rate = 2.0,
                            Sqft = 330,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Officia impedit sapiente esse molestias odio ut ratione perspiciatis voluptatem voluptatem est tempore natus.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 812, DateTimeKind.Local).AddTicks(5179),
                            Details = "Est consequatur dicta voluptas explicabo accusamus tempore consequuntur est velit vel ex maiores dolorem expedita.",
                            ImageUrl = "https://i.picsum.photos/id/602/200/200.jpg?hmac=UQpVCHEMGI1-S-kt8OQLic6TfuG2elfLbLTNDl1mqZE",
                            Name = "Einar Deon Ernser V",
                            Occupancy = 2,
                            Rate = 7.0,
                            Sqft = 201,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Culpa omnis nihil blanditiis itaque ut est voluptates inventore possimus labore voluptate et est voluptas.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 812, DateTimeKind.Local).AddTicks(9411),
                            Details = "Et ad optio atque ea aut vitae molestias cum placeat commodi hic consectetur doloremque.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Dr. Danny Wiegand",
                            Occupancy = 6,
                            Rate = 12.0,
                            Sqft = 134,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "Odit voluptatum ratione qui doloremque nam voluptatem quidem velit soluta.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 813, DateTimeKind.Local).AddTicks(2815),
                            Details = "Dicta doloremque laborum recusandae excepturi atque voluptatem totam aspernatur aperiam.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Gay Rau",
                            Occupancy = 10,
                            Rate = 14.0,
                            Sqft = 226,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "Non voluptate aut qui optio velit et non hic autem molestiae amet aliquid a.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 813, DateTimeKind.Local).AddTicks(6617),
                            Details = "In qui pariatur consectetur blanditiis adipisci nemo dolores laborum quasi consectetur.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Pansy Beier",
                            Occupancy = 9,
                            Rate = 15.0,
                            Sqft = 456,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Amenity = "Recusandae nostrum aut voluptas vitae magni eos ab sequi doloribus perspiciatis nostrum quam reprehenderit.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 814, DateTimeKind.Local).AddTicks(1981),
                            Details = "Id voluptatum quo saepe eos consequatur reiciendis nisi quisquam et debitis ut quo.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Mrs. Cyril Kennedi Cummings",
                            Occupancy = 2,
                            Rate = 4.0,
                            Sqft = 422,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Amenity = "Odio voluptatibus mollitia accusamus voluptatem dolores velit iure qui aut.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 814, DateTimeKind.Local).AddTicks(6936),
                            Details = "Est nam ut reprehenderit magni rerum odit soluta delectus ad voluptate sed est itaque molestiae sit.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Garett Quitzon",
                            Occupancy = 10,
                            Rate = 14.0,
                            Sqft = 486,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Amenity = "Atque animi consequuntur illo recusandae sit sint iure eos quis deleniti error iusto debitis ut.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 815, DateTimeKind.Local).AddTicks(1141),
                            Details = "Doloribus voluptatem aut nam sint iste officia et repudiandae dolorem dolores repellendus ex.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Erna Friesen",
                            Occupancy = 6,
                            Rate = 20.0,
                            Sqft = 267,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Amenity = "Sunt tenetur fuga in quam similique sint cupiditate voluptates quaerat distinctio similique.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 815, DateTimeKind.Local).AddTicks(5280),
                            Details = "Beatae aspernatur aut tempora id eum dolor delectus velit et distinctio perspiciatis sed eius quia.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Leann Robel",
                            Occupancy = 10,
                            Rate = 6.0,
                            Sqft = 315,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Amenity = "Assumenda aut et qui ut corporis adipisci aut vero qui ut blanditiis dolore.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 815, DateTimeKind.Local).AddTicks(9183),
                            Details = "Totam placeat exercitationem facere repellendus non totam deleniti suscipit ratione consequuntur aliquam.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Stephanie Rempel",
                            Occupancy = 2,
                            Rate = 18.0,
                            Sqft = 290,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Amenity = "Quo rerum eos minus totam est eius odit expedita vero laboriosam enim esse est omnis magnam.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 816, DateTimeKind.Local).AddTicks(3567),
                            Details = "Dolore tenetur cupiditate delectus non itaque consequuntur ut nulla eum suscipit ipsa ea deserunt.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Rodger Hermiston",
                            Occupancy = 9,
                            Rate = 7.0,
                            Sqft = 311,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Amenity = "Consequatur rerum sunt magni et nulla nisi necessitatibus soluta nostrum dolorem occaecati quibusdam aliquam.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 816, DateTimeKind.Local).AddTicks(7663),
                            Details = "Voluptatum reiciendis corrupti qui ipsam amet sint sit blanditiis omnis laboriosam doloremque blanditiis.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Wiley Donnelly",
                            Occupancy = 1,
                            Rate = 11.0,
                            Sqft = 395,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Amenity = "Impedit non quasi eos minus quia magni quibusdam fuga adipisci et iusto.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 817, DateTimeKind.Local).AddTicks(2673),
                            Details = "Quas cumque qui voluptatem molestiae sit corrupti voluptatem consectetur reprehenderit.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Dr. Eloise Miracle Waters",
                            Occupancy = 9,
                            Rate = 16.0,
                            Sqft = 288,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Amenity = "Ipsam rerum nulla neque vel repellendus aut illum harum dolores quis esse sed.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 817, DateTimeKind.Local).AddTicks(6800),
                            Details = "Et consequuntur est est sed minima consequuntur alias quod minus cum sed eveniet quo ad.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Felipe Kautzer",
                            Occupancy = 9,
                            Rate = 8.0,
                            Sqft = 134,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Amenity = "Magni tempore officia placeat autem earum enim sequi aut omnis et sapiente voluptatem.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 818, DateTimeKind.Local).AddTicks(718),
                            Details = "Omnis nemo architecto id tempore et ullam reprehenderit autem minus vitae quaerat.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Terrence Barrows",
                            Occupancy = 6,
                            Rate = 14.0,
                            Sqft = 209,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Amenity = "Doloribus magni nesciunt omnis explicabo veritatis beatae distinctio culpa numquam.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 818, DateTimeKind.Local).AddTicks(6017),
                            Details = "Ut autem non ut fuga occaecati qui laborum perspiciatis cumque natus eveniet unde ea est dolorum.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Eunice Liliane Klocko II",
                            Occupancy = 8,
                            Rate = 16.0,
                            Sqft = 205,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Amenity = "Ut est minima quod velit cumque laborum soluta ut placeat commodi delectus sint eaque.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 818, DateTimeKind.Local).AddTicks(9816),
                            Details = "Quia qui pariatur incidunt et ipsum sit dolorum voluptas vel.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Kieran Kris",
                            Occupancy = 9,
                            Rate = 4.0,
                            Sqft = 367,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Amenity = "Reiciendis libero pariatur qui cumque dolorum sed ea qui error consequatur.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 819, DateTimeKind.Local).AddTicks(3915),
                            Details = "Consectetur porro ut architecto animi expedita id est consequatur rerum id qui possimus voluptatem nam at.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Miss Ava Toy DDS",
                            Occupancy = 8,
                            Rate = 4.0,
                            Sqft = 482,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Amenity = "Delectus debitis harum cupiditate vitae error magni corporis ut eum quasi dignissimos nam deserunt.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 819, DateTimeKind.Local).AddTicks(7737),
                            Details = "Fuga dolores dolores iure non recusandae ullam cumque vitae numquam.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Chet Pollich",
                            Occupancy = 4,
                            Rate = 18.0,
                            Sqft = 267,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Amenity = "Sapiente molestias ex alias earum ea sit et fuga qui quos eos.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 820, DateTimeKind.Local).AddTicks(1594),
                            Details = "Eum voluptatem repellendus repellendus nisi soluta nihil et molestias fugiat alias sed architecto.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Magdalena Cummerata",
                            Occupancy = 7,
                            Rate = 4.0,
                            Sqft = 343,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Amenity = "Repellat laboriosam molestiae rerum nobis occaecati culpa veritatis a labore sunt quia consequatur dicta in.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 820, DateTimeKind.Local).AddTicks(7117),
                            Details = "Inventore nesciunt et necessitatibus cumque libero saepe eum quos aut commodi suscipit ut.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Mrs. Shanelle Otha Christiansen II",
                            Occupancy = 8,
                            Rate = 1.0,
                            Sqft = 300,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Amenity = "Quis voluptates tempore dolores aut quae dolores eos praesentium doloremque laborum.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 821, DateTimeKind.Local).AddTicks(780),
                            Details = "Qui corporis magni in explicabo voluptatem et omnis eum eos accusantium.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Ms. Judah Smitham IV",
                            Occupancy = 6,
                            Rate = 20.0,
                            Sqft = 213,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Amenity = "Eligendi suscipit eius aliquam aliquam quia et veniam quis et tenetur sunt.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 821, DateTimeKind.Local).AddTicks(5776),
                            Details = "Magni fugiat a et magni natus cupiditate consectetur voluptatem sit.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Prof. Twila Greg Goodwin V",
                            Occupancy = 5,
                            Rate = 20.0,
                            Sqft = 171,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            Amenity = "Eum rerum eligendi voluptas rerum nemo exercitationem sit odio laboriosam aliquam qui harum porro soluta similique.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 822, DateTimeKind.Local).AddTicks(149),
                            Details = "Voluptas asperiores culpa ex repellat eaque doloremque neque veritatis corporis sed natus voluptatibus fugiat.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Prof. Emmie Cummings",
                            Occupancy = 1,
                            Rate = 9.0,
                            Sqft = 299,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            Amenity = "Fugit modi dolorem ex laudantium architecto modi voluptatem ex illum consequatur officiis facere.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 822, DateTimeKind.Local).AddTicks(5295),
                            Details = "Est minima est vitae maxime in eos ullam omnis deserunt ex.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Prof. Timmy Monserrat Lebsack PhD",
                            Occupancy = 7,
                            Rate = 8.0,
                            Sqft = 395,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            Amenity = "Quas facilis cum et debitis voluptatem itaque labore natus fuga ut.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 825, DateTimeKind.Local).AddTicks(9917),
                            Details = "Sit vitae dolores qui placeat voluptatum quia esse natus et consequatur.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Devon Rosalind Rutherford II",
                            Occupancy = 10,
                            Rate = 12.0,
                            Sqft = 207,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            Amenity = "Quia totam non voluptates officiis id facilis quia iure aut.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 826, DateTimeKind.Local).AddTicks(2082),
                            Details = "Excepturi rerum illo quisquam maiores velit accusantium quia sed consequatur provident ut.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Antonetta Weissnat",
                            Occupancy = 9,
                            Rate = 6.0,
                            Sqft = 435,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            Amenity = "Dolores occaecati non laboriosam et dolores ea quo laudantium dolorem expedita esse dolorem non ipsum.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 826, DateTimeKind.Local).AddTicks(4610),
                            Details = "Amet quo quia laboriosam molestias est et est pariatur reprehenderit qui doloremque eum voluptatem ut.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Sydnie Waters",
                            Occupancy = 10,
                            Rate = 10.0,
                            Sqft = 447,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            Amenity = "Quas aliquid minima suscipit quo velit officiis magni cum veritatis consequuntur molestias.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 826, DateTimeKind.Local).AddTicks(6836),
                            Details = "Praesentium magni incidunt est exercitationem velit maiores repellat omnis enim quia incidunt.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Helene Fadel PhD",
                            Occupancy = 1,
                            Rate = 5.0,
                            Sqft = 114,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            Amenity = "Dolor sequi voluptates dolorum nihil deserunt et libero est quia ab et tempore et modi.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 826, DateTimeKind.Local).AddTicks(9464),
                            Details = "Rerum et et qui ex dicta ab facere tempore est perspiciatis dolores qui magni dolor magnam.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Mr. Gordon Moen",
                            Occupancy = 5,
                            Rate = 18.0,
                            Sqft = 293,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            Amenity = "Veritatis at veniam voluptatem mollitia omnis autem occaecati molestiae nisi impedit voluptatem quo.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 827, DateTimeKind.Local).AddTicks(1868),
                            Details = "Asperiores porro natus voluptatibus enim aliquam corrupti facere hic in iste eos quos quas quaerat.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Michale Nader",
                            Occupancy = 2,
                            Rate = 12.0,
                            Sqft = 111,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            Amenity = "Eveniet ut voluptatem qui architecto assumenda voluptas animi est unde quod.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 827, DateTimeKind.Local).AddTicks(4284),
                            Details = "Iusto repellat vero aut voluptatem voluptatem ratione rerum qui delectus debitis ratione tempora est cumque modi.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Milo Wolf",
                            Occupancy = 2,
                            Rate = 14.0,
                            Sqft = 463,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            Amenity = "Modi adipisci deserunt enim neque voluptates sint unde corrupti ea ducimus sint rem enim.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 827, DateTimeKind.Local).AddTicks(7312),
                            Details = "Numquam qui a veniam at ut veritatis iste sed inventore deleniti.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Bethel Hipolito Hand Jr.",
                            Occupancy = 5,
                            Rate = 11.0,
                            Sqft = 348,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            Amenity = "Qui odit vel qui laborum soluta rerum nostrum molestias molestias et eius maiores nemo.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 827, DateTimeKind.Local).AddTicks(9858),
                            Details = "Sunt saepe quidem ipsum illum voluptatem sit architecto tempora corporis voluptatem praesentium odio pariatur eos sit.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Green Gutmann",
                            Occupancy = 6,
                            Rate = 8.0,
                            Sqft = 433,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            Amenity = "Ratione quidem earum et aut quod modi cupiditate error minima fuga qui.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 828, DateTimeKind.Local).AddTicks(2940),
                            Details = "Omnis quaerat a architecto eum sunt vitae nisi id sequi non aut minus dolorum.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Jensen Candace Witting IV",
                            Occupancy = 10,
                            Rate = 1.0,
                            Sqft = 143,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            Amenity = "Fuga sunt enim ipsum iure ex expedita quisquam veniam ut repellat velit.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 828, DateTimeKind.Local).AddTicks(5195),
                            Details = "Eos hic quia voluptatem nemo molestiae inventore molestiae aperiam delectus qui velit consequatur.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Bernie Kerluke",
                            Occupancy = 2,
                            Rate = 3.0,
                            Sqft = 315,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            Amenity = "Architecto omnis dolor inventore quis quam porro in similique sit velit laboriosam aperiam recusandae sit.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 828, DateTimeKind.Local).AddTicks(8262),
                            Details = "Esse sed ab quisquam quia ut amet et ipsa voluptatibus.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Mr. Joy Evie Swift",
                            Occupancy = 10,
                            Rate = 18.0,
                            Sqft = 314,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            Amenity = "Et dolor dolor est voluptatem quasi nesciunt accusantium rerum occaecati tempore et aut tempore dicta consequatur.",
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 829, DateTimeKind.Local).AddTicks(1501),
                            Details = "Dolor nesciunt est nemo odit quaerat aut excepturi quo quaerat dolore omnis voluptatem.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Mrs. Gerda Trycia Trantow DDS",
                            Occupancy = 2,
                            Rate = 1.0,
                            Sqft = 244,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("VillaNo");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            VillaNo = 101,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 808, DateTimeKind.Local).AddTicks(665),
                            SpecialDetails = "Pariatur voluptates dignissimos quia non et veniam officia necessitatibus distinctio.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 102,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 808, DateTimeKind.Local).AddTicks(1995),
                            SpecialDetails = "Sit cum ullam dolor laborum debitis itaque necessitatibus atque soluta magni sed excepturi.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 103,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 808, DateTimeKind.Local).AddTicks(3478),
                            SpecialDetails = "Expedita corrupti sed et sequi nam quidem expedita ut rerum velit id atque in error.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 104,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 808, DateTimeKind.Local).AddTicks(4945),
                            SpecialDetails = "Placeat quod et enim eaque aut tenetur eaque quia ad qui quo tempore et.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 105,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 808, DateTimeKind.Local).AddTicks(5951),
                            SpecialDetails = "Voluptas libero unde placeat nulla quas numquam rerum incidunt eos.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 106,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 808, DateTimeKind.Local).AddTicks(7051),
                            SpecialDetails = "Quis in sapiente voluptatem rerum sapiente rerum vel alias voluptatum odit dolor.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 107,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 808, DateTimeKind.Local).AddTicks(8175),
                            SpecialDetails = "Est aspernatur eius amet non reprehenderit laudantium animi error vel ut ratione.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 109,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 808, DateTimeKind.Local).AddTicks(9102),
                            SpecialDetails = "Consectetur esse aspernatur fugit cumque dolore qui et est rerum.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 110,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 809, DateTimeKind.Local).AddTicks(413),
                            SpecialDetails = "Impedit maiores sit numquam et qui corporis ducimus alias cum occaecati et voluptas.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 201,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 809, DateTimeKind.Local).AddTicks(1897),
                            SpecialDetails = "Error molestiae aliquam reiciendis et ullam mollitia sit eos et voluptas iure.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 202,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 809, DateTimeKind.Local).AddTicks(3747),
                            SpecialDetails = "Numquam praesentium cum ut possimus excepturi at repudiandae ea quibusdam necessitatibus porro nihil hic.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 203,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 809, DateTimeKind.Local).AddTicks(5540),
                            SpecialDetails = "Animi nesciunt aut eum omnis earum eos eius corporis inventore quibusdam est quod aut ab illum.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 204,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 809, DateTimeKind.Local).AddTicks(7431),
                            SpecialDetails = "Itaque et aut provident dolores iusto enim in qui incidunt itaque ullam doloremque eum.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 205,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 809, DateTimeKind.Local).AddTicks(8884),
                            SpecialDetails = "Maiores iste eligendi accusantium consequuntur error et non sequi veniam deleniti.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 206,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 810, DateTimeKind.Local).AddTicks(918),
                            SpecialDetails = "Culpa aut et eius cumque aperiam nihil dolore exercitationem aut id aspernatur odit autem minus eligendi.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 207,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 810, DateTimeKind.Local).AddTicks(2562),
                            SpecialDetails = "Voluptatibus qui quod atque ipsum itaque id rerum quaerat adipisci qui sint voluptatem inventore et.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 208,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 810, DateTimeKind.Local).AddTicks(4067),
                            SpecialDetails = "Sint odit incidunt error laboriosam tenetur odit accusamus pariatur qui qui assumenda aut quo maxime qui.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 209,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 810, DateTimeKind.Local).AddTicks(5033),
                            SpecialDetails = "Saepe necessitatibus sunt numquam harum eum ut nihil eaque eos.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        },
                        new
                        {
                            VillaNo = 210,
                            CreatedDate = new DateTime(2022, 9, 17, 16, 16, 1, 810, DateTimeKind.Local).AddTicks(6536),
                            SpecialDetails = "Iure libero sint saepe voluptatum mollitia veritatis sit et est et velit sapiente aperiam earum quia.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 2
                        });
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.HasOne("MagicVilla_VillaAPI.Models.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
