// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220911135119_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 585, DateTimeKind.Local).AddTicks(9864),
                            Details = "Sequi sint commodi est qui veritatis maxime odio porro voluptatibus magni quia vel.",
                            ImageUrl = "https://i.picsum.photos/id/778/200/200.jpg?hmac=fgFK_HI_g_N4MzYuYbssOB8ymhT_m0JK61tNJHfdPYU",
                            Name = "Alec Schulist",
                            Occupancy = 9,
                            Rate = 3.0,
                            Sqft = 328,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 586, DateTimeKind.Local).AddTicks(2348),
                            Details = "Neque ipsum maxime cumque iusto recusandae pariatur qui ea cupiditate.",
                            ImageUrl = "https://i.picsum.photos/id/287/200/200.jpg?hmac=kXFCSMZE2rF7NM-EFSH6c_nl5HlKQWvwCdE8JYL-YNQ",
                            Name = "Herman Wehner",
                            Occupancy = 8,
                            Rate = 10.0,
                            Sqft = 430,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 586, DateTimeKind.Local).AddTicks(4857),
                            Details = "Accusamus sed laudantium ullam enim aperiam in aspernatur sequi aliquam.",
                            ImageUrl = "https://i.picsum.photos/id/446/200/200.jpg?hmac=PkaLcCtgL4IvAz-gsxbCXz_tl0qdVUGOrxhYLrywa-c",
                            Name = "Alvera Wilderman",
                            Occupancy = 8,
                            Rate = 2.0,
                            Sqft = 130,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 586, DateTimeKind.Local).AddTicks(8764),
                            Details = "Repellendus modi sunt voluptatem omnis et ipsa officiis dolor qui molestias earum.",
                            ImageUrl = "https://i.picsum.photos/id/602/200/200.jpg?hmac=UQpVCHEMGI1-S-kt8OQLic6TfuG2elfLbLTNDl1mqZE",
                            Name = "Alejandrin Bailey Walsh II",
                            Occupancy = 9,
                            Rate = 8.0,
                            Sqft = 421,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 587, DateTimeKind.Local).AddTicks(1647),
                            Details = "Perspiciatis tempore error illum non repellat eligendi sit molestias quo officia velit unde dolore.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Jimmy Schowalter",
                            Occupancy = 8,
                            Rate = 12.0,
                            Sqft = 410,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 587, DateTimeKind.Local).AddTicks(5601),
                            Details = "Unde amet necessitatibus voluptate qui voluptatibus nulla sint est laborum voluptatum aliquam voluptatem ullam hic id.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Ashlee Heller Sr.",
                            Occupancy = 7,
                            Rate = 11.0,
                            Sqft = 271,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 587, DateTimeKind.Local).AddTicks(9975),
                            Details = "Qui id et est aut eaque voluptatem laboriosam ut ea libero aperiam qui suscipit debitis aut.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Miss Kassandra Triston Frami V",
                            Occupancy = 9,
                            Rate = 1.0,
                            Sqft = 335,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 588, DateTimeKind.Local).AddTicks(2430),
                            Details = "Repellat tempore sit voluptates ut eligendi fugiat eos est qui.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Gladys Schowalter",
                            Occupancy = 4,
                            Rate = 20.0,
                            Sqft = 326,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 588, DateTimeKind.Local).AddTicks(5028),
                            Details = "Dolor optio neque eveniet et voluptas dolorem labore nisi ut est.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Vern Luettgen Sr.",
                            Occupancy = 2,
                            Rate = 4.0,
                            Sqft = 126,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 588, DateTimeKind.Local).AddTicks(8846),
                            Details = "Voluptatem et nihil doloribus sint quod quidem commodi error fugit amet.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Ms. Ofelia Tatum Simonis",
                            Occupancy = 10,
                            Rate = 1.0,
                            Sqft = 263,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 589, DateTimeKind.Local).AddTicks(2950),
                            Details = "Ratione facere tenetur sapiente quibusdam veniam occaecati reiciendis ut earum voluptate dolorem corrupti debitis.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Mrs. Lucas Lura Franecki",
                            Occupancy = 3,
                            Rate = 20.0,
                            Sqft = 239,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 589, DateTimeKind.Local).AddTicks(5608),
                            Details = "Dolorem nulla ipsa aut est officiis et aut maxime aut velit sed.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Domingo Braun MD",
                            Occupancy = 4,
                            Rate = 16.0,
                            Sqft = 472,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 589, DateTimeKind.Local).AddTicks(8639),
                            Details = "Iste dolores pariatur et reiciendis velit repellat culpa explicabo est enim itaque cum unde ea inventore.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Derek Watsica",
                            Occupancy = 8,
                            Rate = 3.0,
                            Sqft = 400,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 590, DateTimeKind.Local).AddTicks(1238),
                            Details = "Necessitatibus atque atque sit nemo laborum incidunt voluptatibus qui quia ut.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Mr. Leta Robel",
                            Occupancy = 6,
                            Rate = 7.0,
                            Sqft = 487,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 590, DateTimeKind.Local).AddTicks(3695),
                            Details = "Neque consequuntur nam aut dicta id temporibus odio cum dolores.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Jakob Rodriguez",
                            Occupancy = 9,
                            Rate = 19.0,
                            Sqft = 478,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 590, DateTimeKind.Local).AddTicks(6147),
                            Details = "Ut earum iure dignissimos amet reiciendis consectetur laudantium velit quis.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Burdette Nikolaus",
                            Occupancy = 7,
                            Rate = 18.0,
                            Sqft = 448,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 590, DateTimeKind.Local).AddTicks(8870),
                            Details = "Consequatur quo qui accusantium consequatur enim at quae cum animi aut iusto velit.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Samanta Turcotte",
                            Occupancy = 5,
                            Rate = 6.0,
                            Sqft = 222,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 591, DateTimeKind.Local).AddTicks(1615),
                            Details = "Sint perspiciatis dignissimos natus eos dolorem molestiae pariatur dolorem at commodi ex laborum.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Isaias Keeling",
                            Occupancy = 7,
                            Rate = 1.0,
                            Sqft = 358,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 591, DateTimeKind.Local).AddTicks(5566),
                            Details = "Quasi ea nihil architecto laboriosam dignissimos exercitationem suscipit error corrupti sapiente et.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Jade Vella Williamson PhD",
                            Occupancy = 4,
                            Rate = 18.0,
                            Sqft = 346,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 591, DateTimeKind.Local).AddTicks(8528),
                            Details = "Rerum et architecto consequatur et est laboriosam sed nostrum optio a et velit esse hic.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Prof. Marcelo Runolfsson",
                            Occupancy = 5,
                            Rate = 15.0,
                            Sqft = 246,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 592, DateTimeKind.Local).AddTicks(1170),
                            Details = "Commodi labore sapiente rerum ut enim nostrum unde voluptates non veritatis quia.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Laron Feil",
                            Occupancy = 1,
                            Rate = 4.0,
                            Sqft = 398,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 592, DateTimeKind.Local).AddTicks(3785),
                            Details = "Illo est consequuntur blanditiis eum dolorem recusandae dolorem occaecati consequatur perspiciatis.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Mr. Tamia Ledner PhD",
                            Occupancy = 3,
                            Rate = 8.0,
                            Sqft = 170,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 592, DateTimeKind.Local).AddTicks(6320),
                            Details = "Numquam facilis exercitationem voluptatem nemo impedit sunt non molestias vero et.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Randi Bogan",
                            Occupancy = 5,
                            Rate = 9.0,
                            Sqft = 451,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 592, DateTimeKind.Local).AddTicks(8963),
                            Details = "Ex rerum sit voluptatum quisquam id ut nam labore veritatis delectus qui.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Dorothy Schinner",
                            Occupancy = 6,
                            Rate = 9.0,
                            Sqft = 206,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 593, DateTimeKind.Local).AddTicks(1414),
                            Details = "Porro numquam id rem sapiente est dolor ea reprehenderit quo.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Hunter Collier",
                            Occupancy = 10,
                            Rate = 16.0,
                            Sqft = 364,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 593, DateTimeKind.Local).AddTicks(4093),
                            Details = "Qui omnis doloribus accusamus aut velit dicta impedit excepturi impedit consequuntur perferendis.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Randal Douglas",
                            Occupancy = 6,
                            Rate = 20.0,
                            Sqft = 366,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 593, DateTimeKind.Local).AddTicks(6617),
                            Details = "Debitis facilis aut sint dolor fugiat suscipit rerum voluptas est.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Tomasa Barton",
                            Occupancy = 5,
                            Rate = 13.0,
                            Sqft = 173,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 594, DateTimeKind.Local).AddTicks(727),
                            Details = "Quis sunt sit omnis temporibus velit et ut voluptas sunt commodi blanditiis illum qui.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Prof. Celestine Chanel Romaguera DDS",
                            Occupancy = 2,
                            Rate = 4.0,
                            Sqft = 142,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 594, DateTimeKind.Local).AddTicks(3380),
                            Details = "Laudantium assumenda magnam vitae sunt ut error officiis possimus sapiente debitis molestiae.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Sam Hudson PhD",
                            Occupancy = 5,
                            Rate = 12.0,
                            Sqft = 208,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 594, DateTimeKind.Local).AddTicks(6232),
                            Details = "Qui et voluptatum asperiores adipisci sed molestias corrupti totam suscipit magnam voluptatibus ullam.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Zoila Runolfsson",
                            Occupancy = 3,
                            Rate = 14.0,
                            Sqft = 275,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 594, DateTimeKind.Local).AddTicks(9957),
                            Details = "Praesentium error dolorem laudantium animi voluptas porro sapiente corrupti ut.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Prof. Adell Anissa Wolf III",
                            Occupancy = 2,
                            Rate = 17.0,
                            Sqft = 238,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 595, DateTimeKind.Local).AddTicks(3014),
                            Details = "Sed esse itaque tempore eaque mollitia omnis magnam eligendi qui repellat nulla minus qui accusamus.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Betty Glover",
                            Occupancy = 6,
                            Rate = 10.0,
                            Sqft = 430,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 595, DateTimeKind.Local).AddTicks(6152),
                            Details = "Et doloremque aliquam et officiis quis neque maxime ut veritatis temporibus ratione consequatur ut cum.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Russell Lindgren PhD",
                            Occupancy = 5,
                            Rate = 11.0,
                            Sqft = 427,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 595, DateTimeKind.Local).AddTicks(9094),
                            Details = "Facilis aut et blanditiis aut culpa a est sint ut esse id et quis exercitationem.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Elton Muller",
                            Occupancy = 3,
                            Rate = 3.0,
                            Sqft = 109,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 596, DateTimeKind.Local).AddTicks(3803),
                            Details = "Impedit tempora sint qui voluptatem est id dolorum accusantium consequatur animi aut laboriosam qui perspiciatis sit.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Prof. Monroe Andy Kertzmann",
                            Occupancy = 5,
                            Rate = 7.0,
                            Sqft = 425,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 596, DateTimeKind.Local).AddTicks(6707),
                            Details = "Molestias itaque velit nihil aut dolorem dolores dolore beatae animi quo.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Prof. Chelsea Stamm",
                            Occupancy = 7,
                            Rate = 18.0,
                            Sqft = 320,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 597, DateTimeKind.Local).AddTicks(1535),
                            Details = "Recusandae odit nisi facilis tenetur nesciunt adipisci et laborum cumque corrupti quam aut reprehenderit eveniet aperiam.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Bradley Samara Zieme DVM",
                            Occupancy = 6,
                            Rate = 9.0,
                            Sqft = 391,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 597, DateTimeKind.Local).AddTicks(4761),
                            Details = "Dolorem quibusdam autem qui doloribus quas animi expedita amet possimus eaque iure nam.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Karianne Gulgowski",
                            Occupancy = 6,
                            Rate = 1.0,
                            Sqft = 258,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 597, DateTimeKind.Local).AddTicks(9606),
                            Details = "Rerum hic ut est a possimus amet magni ea ratione et fugiat molestiae velit.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Hosea Federico Marks Jr.",
                            Occupancy = 5,
                            Rate = 4.0,
                            Sqft = 484,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            Amenity = "",
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 598, DateTimeKind.Local).AddTicks(2661),
                            Details = "Iste ut ducimus fugiat qui rerum quasi possimus dolores earum in similique.",
                            ImageUrl = "https://i.picsum.photos/id/58/200/200.jpg?hmac=aol3E3KC2fpsVXlPhgxLR9-CLoUQa-kbswhZx-gYzCE",
                            Name = "Hudson Hills",
                            Occupancy = 9,
                            Rate = 9.0,
                            Sqft = 268,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("VillaNo");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            VillaNo = 101,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 584, DateTimeKind.Local).AddTicks(7289),
                            SpecialDetails = "Maiores autem in tempore veritatis eveniet sapiente dignissimos consequatur corrupti laudantium laboriosam repellendus.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 102,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 584, DateTimeKind.Local).AddTicks(8554),
                            SpecialDetails = "Tenetur ipsam suscipit consectetur aut quibusdam cumque aut atque sed et accusantium.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 103,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 584, DateTimeKind.Local).AddTicks(9503),
                            SpecialDetails = "Et reiciendis accusamus placeat atque odit laboriosam velit est saepe.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 104,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 585, DateTimeKind.Local).AddTicks(1018),
                            SpecialDetails = "Quae consectetur sunt fugiat vel voluptas et incidunt qui non aspernatur labore eos et dolorem at.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 105,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 585, DateTimeKind.Local).AddTicks(2142),
                            SpecialDetails = "Magnam et et ab ad porro omnis maxime commodi doloribus nihil a.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 106,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 585, DateTimeKind.Local).AddTicks(3223),
                            SpecialDetails = "Sequi quisquam totam voluptas neque et quia alias enim aut non.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 107,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 585, DateTimeKind.Local).AddTicks(4311),
                            SpecialDetails = "Quis omnis voluptas molestiae accusantium ex vitae doloribus ratione sit ut.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 109,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 585, DateTimeKind.Local).AddTicks(5743),
                            SpecialDetails = "Aut deleniti non labore eligendi voluptas repellendus delectus ut ut voluptatem fugiat qui aut tenetur.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        },
                        new
                        {
                            VillaNo = 110,
                            CreatedDate = new DateTime(2022, 9, 11, 15, 51, 19, 585, DateTimeKind.Local).AddTicks(6771),
                            SpecialDetails = "Dolore placeat animi praesentium sint est et dolores laudantium soluta aliquam.",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VillaId = 1
                        });
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.HasOne("MagicVilla_VillaAPI.Models.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
